export const GET_ADMINS = "GET_ADMINS";
export const GET_ADMINS_SUCCESS = "GET_ADMINS_SUCCESS";
export const GET_ADMINS_FAIL = "GET_ADMINS_FAIL";

export const GET_ADMIN = "GET_ADMIN";
export const GET_ADMIN_SUCCESS = "GET_ADMIN_SUCCESS";
export const GET_ADMIN_FAIL = "GET_ADMIN_FAIL";

export const GET_ADMIN_PROFILE = "GET_ADMIN_PROFILE";
export const GET_ADMIN_PROFILE_SUCCESS = "GET_ADMIN_PROFILE_SUCCESS";
export const GET_ADMIN_PROFILE_FAIL = "GET_ADMIN_PROFILE_FAIL";

export const POST_ADMIN_LOGIN = "POST_ADMIN_LOGIN";
export const POST_ADMIN_LOGIN_SUCCESS = "POST_ADMIN_LOGIN_SUCCESS";
export const POST_ADMIN_LOGIN_FAIL = "POST_ADMIN_LOGIN_FAIL";

export const POST_ADMIN_LOGOUT = "POST_ADMIN_LOGOUT";
export const POST_ADMIN_LOGOUT_SUCCESS = "POST_ADMIN_LOGOUT_SUCCESS";
export const POST_ADMIN_LOGOUT_FAIL = "POST_ADMIN_LOGOUT_FAIL";

export const POST_ADMIN_REGISTER = "POST_ADMIN_REGISTER";
export const POST_ADMIN_REGISTER_SUCCESS = "POST_ADMIN_REGISTER_SUCCESS";
export const POST_ADMIN_REGISTER_FAIL = "POST_ADMIN_REGISTER_FAIL";

export const POST_ADD_ADMIN = "POST_ADD_ADMIN";
export const POST_ADD_ADMIN_SUCCESS = "POST_ADD_ADMIN_SUCCESS";
export const POST_ADD_ADMIN_FAIL = "POST_ADD_ADMIN_FAIL";

export const PUT_ADMIN_PROFILE = "PUT_ADMIN";
export const PUT_ADMIN_PROFILE_SUCCESS = "PUT_ADMIN_PROFILE_SUCCESS";
export const PUT_ADMIN_PROFILE_FAIL = "PUT_ADMIN_PROFILE_FAIL";

export const DELETE_ADMIN = "DELETE_ADMIN";
export const DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS";
export const DELETE_ADMIN_FAIL = "DELETE_ADMIN_FAIL";
